# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 03:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0003_auto_20161228_2231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='description',
        ),
    ]
