# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 19:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0004_remove_food_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Meals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('calories', models.DecimalField(decimal_places=3, max_digits=5)),
                ('protein', models.DecimalField(decimal_places=3, max_digits=5)),
                ('carbs', models.DecimalField(decimal_places=3, max_digits=5)),
                ('fat', models.DecimalField(decimal_places=3, max_digits=5)),
                ('foods', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MealPlan.Food')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('mealPlans', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MealPlan.MealPlan')),
            ],
        ),
        migrations.AddField(
            model_name='mealplan',
            name='meals',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MealPlan.Meals'),
        ),
    ]
