# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0005_auto_20170108_1441'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meals',
            new_name='Meal',
        ),
    ]
