# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-08 22:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MealPlan', '0007_auto_20170108_1701'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='User',
        ),
    ]
